const MOVIES_LIST = [ 
  { title: "Joker", price: 800, rating: 8.5 },
  { title: "Batman begins", price: 850, rating: 8.2 },
  { title: "Deadpoool", price: 730, rating: 8.0 },
  { title: "Logan", price: 810, rating: 8.1 },
  { title: "Unforgiven", price: 870, rating: 8.2 },
  { title: "Lord Of The Rings: The Two Towers", price: 900, rating: 8.7 },
  { title: "Matrix", price: 770, rating: 8.7 },
  { title: "Interstellar", price: 840, rating: 8.6 },
  { title: "Star Trek: Kirk", price: 820, rating: 7.9 },
  { title: "2001: A Space Odyssey", price: 950, rating: 8.3 },
  { title: "Bram Stroker's Dracula", price: 880, rating: 7.4 },
  { title: "Alien", price: 780, rating: 8.4 },
  { title: "Die Brücke", price: 750, rating: 8.0 },
  { title: "Seven Samurai", price: 760, rating: 8.6 },
  { title: "The Great Dictator", price: 790, rating: 8.4 }
];

const CURRENCIES = [
  {short: "AED", name: "United Arab Emirates Dirham", symbol: "", trigram: true, display: true },
  {short: "AFN", name: "Afghan Afghani", symbol: "", trigram: true, display: false },
  {short: "ALL", name: "Albanian Lek", symbol: "", trigram: true, display: false },
  {short: "AMD", name: "Armenian Dram", symbol: "", trigram: true, display: false },
  {short: "ANG", name: "Netherlands Antillean Guilder", symbol: "", trigram: true, display: false },
  {short: "AOA", name: "Angolan Kwanza", symbol: "", trigram: true, display: false },
  {short: "ARS", name: "Argentine Peso", symbol: "", trigram: true, display: true },
  {short: "AUD", name: "Australian Dollar", symbol: "", trigram: true, display: true },
  {short: "AWG", name: "Aruban Florin", symbol: "", trigram: true, display: false },
  {short: "AZN", name: "Azerbaijani Manat", symbol: "", trigram: true, display: false },
  {short: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "", trigram: true, display: false },
  {short: "BBD", name: "Barbadian Dollar", symbol: "", trigram: true, display: false },
  {short: "BDT", name: "Bangladeshi Taka", symbol: "", trigram: true, display: false },
  {short: "BGN", name: "Bulgarian Lev", symbol: "", trigram: true, display: true },
  {short: "BHD", name: "Bahraini Dinar", symbol: "", trigram: true, display: false },
  {short: "BIF", name: "Burundian Franc", symbol: "", trigram: true, display: false },
  {short: "BMD", name: "Bermudan Dollar", symbol: "", trigram: true, display: false },
  {short: "BND", name: "Brunei Dollar", symbol: "", trigram: true, display: false },
  {short: "BOB", name: "Bolivian Boliviano", symbol: "", trigram: true, display: false },
  {short: "BRL", name: "Brazilian Real", symbol: "R$", trigram: false, display: true },
  {short: "BSD", name: "Bahamian Dollar", symbol: "", trigram: true, display: true },
  {short: "BTC", name: "Bitcoin", symbol: "", trigram: true, display: false },
  {short: "BTN", name: "Bhutanese Ngultrum", symbol: "", trigram: true, display: false },
  {short: "BWP", name: "Botswanan Pula", symbol: "", trigram: true, display: false },
  {short: "BYN", name: "Belarusian Ruble", symbol: "", trigram: true, display: false },
  {short: "BZD", name: "Belize Dollar", symbol: "", trigram: true, display: false },
  {short: "CAD", name: "Canadian Dollar", symbol: "", trigram: true, display: true },
  {short: "CDF", name: "Congolese Franc", symbol: "", trigram: true, display: false },
  {short: "CHF", name: "Swiss Franc", symbol: "", trigram: true, display: true },
  {short: "CLF", name: "Chilean Unit of Account (UF)", symbol: "", trigram: true, display: false },
  {short: "CLP", name: "Chilean Peso", symbol: "", trigram: true, display: true },
  {short: "CNH", name: "Chinese Yuan (Offshore)", symbol: "¥", trigram: true, display: false },
  {short: "CNY", name: "Chinese Yuan", symbol: "¥", trigram: true, display: true },
  {short: "COP", name: "Colombian Peso", symbol: "", trigram: true, display: true },
  {short: "CRC", name: "Costa Rican Colón", symbol: "", trigram: true, display: false },
  {short: "CUC", name: "Cuban Convertible Peso", symbol: "", trigram: true, display: false },
  {short: "CUP", name: "Cuban Peso", symbol: "", trigram: true, display: false },
  {short: "CVE", name: "Cape Verdean Escudo", symbol: "", trigram: true, display: false },
  {short: "CZK", name: "Czech Republic Koruna", symbol: "", trigram: true, display: true },
  {short: "DJF", name: "Djiboutian Franc", symbol: "", trigram: true, display: false },
  {short: "DKK", name: "Danish Krone", symbol: "", trigram: true, display: true },
  {short: "DOP", name: "Dominican Peso", symbol: "", trigram: true, display: true },
  {short: "DZD", name: "Algerian Dinar", symbol: "", trigram: true, display: false },
  {short: "EGP", name: "Egyptian Pound", symbol: "", trigram: true, display: true },
  {short: "ERN", name: "Eritrean Nakfa", symbol: "", trigram: true, display: false },
  {short: "ETB", name: "Ethiopian Birr", symbol: "", trigram: true, display: false },
  {short: "EUR", name: "Euro", symbol: "€", trigram: false, display: false },
  {short: "FJD", name: "Fijian Dollar", symbol: "", trigram: true, display: true },
  {short: "FKP", name: "Falkland Islands Pound", symbol: "", trigram: true, display: false },
  {short: "GBP", name: "British Pound Sterling", symbol: "£", trigram: false, display: true },
  {short: "GEL", name: "Georgian Lari", symbol: "", trigram: true, display: false },
  {short: "GGP", name: "Guernsey Pound", symbol: "", trigram: true, display: false },
  {short: "GHS", name: "Ghanaian Cedi", symbol: "", trigram: true, display: false },
  {short: "GIP", name: "Gibraltar Pound", symbol: "", trigram: true, display: false },
  {short: "GMD", name: "Gambian Dalasi", symbol: "", trigram: true, display: false },
  {short: "GNF", name: "Guinean Franc", symbol: "", trigram: true, display: false },
  {short: "GTQ", name: "Guatemalan Quetzal", symbol: "", trigram: true, display: true },
  {short: "GYD", name: "Guyanaese Dollar", symbol: "", trigram: true, display: false },
  {short: "HKD", name: "Hong Kong Dollar", symbol: "", trigram: true, display: true },
  {short: "HNL", name: "Honduran Lempira", symbol: "", trigram: true, display: false },
  {short: "HRK", name: "Croatian Kuna", symbol: "", trigram: true, display: true },
  {short: "HTG", name: "Haitian Gourde", symbol: "", trigram: true, display: false },
  {short: "HUF", name: "Hungarian Forint", symbol: "Ft", trigram: false, display: true },
  {short: "IDR", name: "Indonesian Rupiah", symbol: "", trigram: true, display: true },
  {short: "ILS", name: "Israeli New Sheqel", symbol: "₪", trigram: false, display: true },
  {short: "IMP", name: "Manx pound", symbol: "", trigram: true, display: false },
  {short: "INR", name: "Indian Rupee", symbol: "", trigram: true, display: true },
  {short: "IQD", name: "Iraqi Dinar", symbol: "", trigram: true, display: false },
  {short: "IRR", name: "Iranian Rial", symbol: "", trigram: true, display: false },
  {short: "ISK", name: "Icelandic Króna", symbol: "kr", trigram: false, display: true },
  {short: "JEP", name: "Jersey Pound", symbol: "", trigram: true, display: false },
  {short: "JMD", name: "Jamaican Dollar", symbol: "J$", trigram: false, display: false },
  {short: "JOD", name: "Jordanian Dinar", symbol: "", trigram: true, display: false },
  {short: "JPY", name: "Japanese Yen", symbol: "¥", trigram: false, display: true },
  {short: "KES", name: "Kenyan Shilling", symbol: "", trigram: true, display: false },
  {short: "KGS", name: "Kyrgystani Som", symbol: "", trigram: true, display: false },
  {short: "KHR", name: "Cambodian Riel", symbol: "", trigram: true, display: false },
  {short: "KMF", name: "Comorian Franc", symbol: "", trigram: true, display: false },
  {short: "KPW", name: "North Korean Won", symbol: "₩", trigram: true, display: false },
  {short: "KRW", name: "South Korean Won", symbol: "₩", trigram: false, display: true },
  {short: "KWD", name: "Kuwaiti Dinar", symbol: "", trigram: true, display: false },
  {short: "KYD", name: "Cayman Islands Dollar", symbol: "", trigram: true, display: false },
  {short: "KZT", name: "Kazakhstani Tenge", symbol: "", trigram: true, display: true },
  {short: "LAK", name: "Laotian Kip", symbol: "₭", trigram: true, display: false },
  {short: "LBP", name: "Lebanese Pound", symbol: "", trigram: true, display: false },
  {short: "LKR", name: "Sri Lankan Rupee", symbol: "", trigram: true, display: false },
  {short: "LRD", name: "Liberian Dollar", symbol: "", trigram: true, display: false },
  {short: "LSL", name: "Lesotho Loti", symbol: "", trigram: true, display: false },
  {short: "LYD", name: "Libyan Dinar", symbol: "", trigram: true, display: false },
  {short: "MAD", name: "Moroccan Dirham", symbol: "", trigram: true, display: false },
  {short: "MDL", name: "Moldovan Leu", symbol: "", trigram: true, display: false },
  {short: "MGA", name: "Malagasy Ariary", symbol: "", trigram: true, display: false },
  {short: "MKD", name: "Macedonian Denar", symbol: "ден", trigram: false, display: false },
  {short: "MMK", name: "Myanma Kyat", symbol: "", trigram: true, display: false },
  {short: "MNT", name: "Mongolian Tugrik", symbol: "₮", trigram: false, display: false },
  {short: "MOP", name: "Macanese Pataca", symbol: "", trigram: true, display: false },
  {short: "MRO", name: "Mauritanian Ouguiya (pre-2018)", symbol: "", trigram: true, display: false },
  {short: "MRU", name: "Mauritanian Ouguiya", symbol: "", trigram: true, display: false },
  {short: "MUR", name: "Mauritian Rupee", symbol: "₨", trigram: false, display: false },
  {short: "MVR", name: "Maldivian Rufiyaa", symbol: "", trigram: true, display: true },
  {short: "MWK", name: "Malawian Kwacha", symbol: "", trigram: true, display: false },
  {short: "MXN", name: "Mexican Peso", symbol: "", trigram: true, display: true },
  {short: "MYR", name: "Malaysian Ringgit", symbol: "", trigram: true, display: true },
  {short: "MZN", name: "Mozambican Metical", symbol: "", trigram: true, display: false },
  {short: "NAD", name: "Namibian Dollar", symbol: "", trigram: true, display: false },
  {short: "NGN", name: "Nigerian Naira", symbol: "₦", trigram: false, display: false },
  {short: "NIO", name: "Nicaraguan Córdoba", symbol: "", trigram: true, display: false },
  {short: "NOK", name: "Norwegian Krone", symbol: "", trigram: true, display: true },
  {short: "NPR", name: "Nepalese Rupee", symbol: "", trigram: true, display: false },
  {short: "NZD", name: "New Zealand Dollar", symbol: "", trigram: true, display: true },
  {short: "OMR", name: "Omani Rial", symbol: "", trigram: true, display: false },
  {short: "PAB", name: "Panamanian Balboa", symbol: "B/.", trigram: false, display: true },
  {short: "PEN", name: "Peruvian Nuevo Sol", symbol: "S/.", trigram: false, display: true },
  {short: "PGK", name: "Papua New Guinean Kina", symbol: "", trigram: true, display: false },
  {short: "PHP", name: "Philippine Peso", symbol: "₱", trigram: false, display: true },
  {short: "PKR", name: "Pakistani Rupee", symbol: "", trigram: true, display: true },
  {short: "PLN", name: "Polish Zloty", symbol: "zł", trigram: false, display: true },
  {short: "PYG", name: "Paraguayan Guarani", symbol: "Gs", trigram: false, display: true },
  {short: "QAR", name: "Qatari Rial", symbol: "", trigram: true, display: false },
  {short: "RON", name: "Romanian Leu", symbol: "lei", trigram: false, display: true },
  {short: "RSD", name: "Serbian Dinar", symbol: "Дин.", trigram: false, display: false },
  {short: "RUB", name: "Russian Ruble", symbol: "₽", trigram: false, display: true },
  {short: "RWF", name: "Rwandan Franc", symbol: "", trigram: true, display: false },
  {short: "SAR", name: "Saudi Riyal", symbol: "", trigram: true, display: true },
  {short: "SBD", name: "Solomon Islands Dollar", symbol: "", trigram: true, display: false },
  {short: "SCR", name: "Seychellois Rupee", symbol: "", trigram: true, display: false },
  {short: "SDG", name: "Sudanese Pound", symbol: "", trigram: true, display: false },
  {short: "SEK", name: "Swedish Krona", symbol: "", trigram: true, display: true },
  {short: "SGD", name: "Singapore Dollar", symbol: "", trigram: true, display: true },
  {short: "SHP", name: "Saint Helena Pound", symbol: "", trigram: true, display: false },
  {short: "SLL", name: "Sierra Leonean Leone", symbol: "", trigram: true, display: false },
  {short: "SOS", name: "Somali Shilling", symbol: "", trigram: true, display: false },
  {short: "SRD", name: "Surinamese Dollar", symbol: "", trigram: true, display: false },
  {short: "SSP", name: "South Sudanese Pound", symbol: "", trigram: true, display: false },
  {short: "STD", name: "São Tomé and Príncipe Dobra (pre-2018)", symbol: "", trigram: true, display: false },
  {short: "STN", name: "São Tomé and Príncipe Dobra", symbol: "", trigram: true, display: false },
  {short: "SVC", name: "Salvadoran Colón", symbol: "", trigram: true, display: false },
  {short: "SYP", name: "Syrian Pound", symbol: "", trigram: true, display: false },
  {short: "SZL", name: "Swazi Lilangeni", symbol: "", trigram: true, display: false },
  {short: "THB", name: "Thai Baht", symbol: "", trigram: true, display: true },
  {short: "TJS", name: "Tajikistani Somoni", symbol: "", trigram: true, display: false },
  {short: "TMT", name: "Turkmenistani Manat", symbol: "", trigram: true, display: false },
  {short: "TND", name: "Tunisian Dinar", symbol: "", trigram: true, display: false },
  {short: "TOP", name: "Tongan Pa'anga", symbol: "", trigram: true, display: false },
  {short: "TRY", name: "Turkish Lira", symbol: "", trigram: true, display: true },
  {short: "TTD", name: "Trinidad and Tobago Dollar", symbol: "", trigram: true, display: false },
  {short: "TWD", name: "New Taiwan Dollar", symbol: "NT$", trigram: false, display: true },
  {short: "TZS", name: "Tanzanian Shilling", symbol: "", trigram: true, display: false },
  {short: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", trigram: false, display: true },
  {short: "UGX", name: "Ugandan Shilling", symbol: "", trigram: true, display: false },
  {short: "USD", name: "United States Dollar", symbol: "$", trigram: false, display: true },
  {short: "UYU", name: "Uruguayan Peso", symbol: "", trigram: true, display: true },
  {short: "UZS", name: "Uzbekistan Som", symbol: "", trigram: true, display: false },
  {short: "VEF", name: "Venezuelan Bolívar Fuerte (Old)", symbol: "", trigram: true, display: false },
  {short: "VES", name: "Venezuelan Bolívar Soberano", symbol: "", trigram: true, display: false },
  {short: "VND", name: "Vietnamese Dong", symbol: "₫", trigram: false, display: false },
  {short: "VUV", name: "Vanuatu Vatu", symbol: "", trigram: true, display: false },
  {short: "WST", name: "Samoan Tala", symbol: "", trigram: true, display: false },
  {short: "XAF", name: "CFA Franc BEAC", symbol: "", trigram: true, display: false },
  {short: "XCD", name: "East Caribbean Dollar", symbol: "", trigram: true, display: false },
  {short: "XDR", name: "Special Drawing Rights", symbol: "", trigram: true, display: false },
  {short: "XOF", name: "CFA Franc BCEAO", symbol: "", trigram: true, display: false },
  {short: "XPF", name: "CFP Franc", symbol: "", trigram: true, display: false },
  {short: "YER", name: "Yemeni Rial", symbol: "", trigram: true, display: false },
  {short: "ZAR", name: "South African Rand", symbol: "", trigram: true, display: true },
  {short: "ZMW", name: "Zambian Kwacha", symbol: "", trigram: true, display: false },
  {short: "ZWL", name: "Zimbabwean Dollar", symbol: "", trigram: true, display: false }
];